[technote]
id = "TSTN-046"
series_id = "TSTN"
canonical_url = "https://tstn-046.lsst.io"
github_url = "https://github.com/lsst-tstn/tstn-046"
github_default_branch = "main"
date_created = 2024-07-19T01:02:16Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "stable"

[[technote.authors]]
name.given = "Tiago"
name.family = "Ribeiro"
internal_id = "ribeirot"

[[technote.authors]]
name.given = "Michael"
name.family = "Reuter"
internal_id = "reuterma"

[[technote.authors]]
name.given = "Sebastian"
name.family = "Aranda"

[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
